# config.yml for MobMoney
# v1.0.2

# General settings.
general:
  consoleoutput: false
  moneyfromspawners: false
  
# Amounts.
# Setting any of these vaules to "0" or less will disable rewards for that mob.
amounts:
  passive:
    bat: 0.0
    chicken: 0.0
    cow: 0.0
    horse: 0.0
    mooshroom: 0.0
    ocelot: 0.0
    pig: 0.0
    rabbit: 0.0
    sheep: 0.0
    squid: 0.0
    villager: 0.0
  
  aggressive:
    blaze: 0.0
    cavespider: 0.0
    creeper: 0.0
    elderguardian: 0.0
    enderdragon: 0.0
    enderman: 0.0
    endermite: 0.0
    ghast: 0.0
    giant: 0.0
    guardian: 0.0
    irongolem: 0.0
    killerrabbit: 0.0
    magmacube: 0.0
    silverfish: 0.0
    skeleton: 0.0
    slime: 0.0
    spider: 0.0
    witch: 0.0
    wither: 0.0
    witherskeleton: 0.0
    wolf: 0.0
    zombie: 0.0
    zombiepig: 0.0